### ISSUE TITLE
create flag for Incomplete course history 

### ISSUE THREAD

**Issue by jmhernan** [CCER-RMP/cadrs#13]
I'm doing some validation checks and have a list of "to-dos" but was hoping I could get some assistance on this one. 
Issue: The student grade history file has student records of students throughout their high school years. Some students are missing records in a year or multiple years.

example:
Student # 124: courses in only 11th and 12th grade 
Student # 125: Is missing all of 9th grade

Ideally simple version:
Take the Student Grade History file and output something like this:

|studentID|Complete HS Records|
|------|------|
|123|1|
|124|0|
|125|0|
|126|1| 

The logic will require some thinking:

1. The easy one is at least one record per grade level (9-12) some have middle school grades
2. A minimum of credits attempted per grade level 
3. Others?

Done in `sql` preferably but whatever gets the job done is fine.

**Comment by codeforkjeff** [comment]
Here's two queries for the logic you sketched out, to give you a sense of the resulting counts.

```
DROP TABLE IF EXISTS #CompleteHSRecordsSimple;

WITH DistinctGradeLevelCounts AS (
	SELECT
		SSID,
		COUNT(DISTINCT GradeLevelWhenCourseTaken) AS DistinctGradeLevelCount
	FROM Final.StudentGradeHistory
	WHERE 
		GradeLevelWhenCourseTaken IN (9, 10, 11, 12)
	GROUP BY SSID
)
SELECT 
	*,
	CASE WHEN DistinctGradeLevelCount = 4 THEN 1 ELSE 0 END AS CompleteHSRecords
INTO #CompleteHSRecordsSimple
FROM DistinctGradeLevelCounts;

-- out of 169,448 students that have any HS grades in SGH, 76,061 have complete transcripts
SELECT
	SUM(CompleteHSRecords) AS CompleteHSRecords,
	COUNT(*) 
FROM #CompleteHSRecordsSimple

-----------------------------------------

DROP TABLE IF EXISTS #CompleteHSRecordsUsingMinCredits;

WITH CreditsAttemptedTotals AS (
	SELECT
		SSID,
		GradeLevelWhenCourseTaken,
		SUM(CreditsAttempted) AS CreditsAttemptedTotal,
		CASE WHEN SUM(CreditsAttempted) >= 6.0 THEN 1 ELSE 0 END AS HasMinCredits
	FROM Final.StudentGradeHistory
	WHERE 
		GradeLevelWhenCourseTaken IN (9, 10, 11, 12)
	GROUP BY
		SSID,
		GradeLevelWhenCourseTaken
)
SELECT
	SSID,
	CASE WHEN(COUNT(DISTINCT GradeLevelWhenCourseTaken) = 4 AND COUNT(DISTINCT GradeLevelWhenCourseTaken) = SUM(HasMinCredits)) THEN 1 ELSE 0 END AS CompleteHSRecords
INTO #CompleteHSRecordsUsingMinCredits
FROM CreditsAttemptedTotals
GROUP BY SSID;

-- out of 169,448 students that have any HS grades in SGH, 34,980 have complete transcripts when counting minimum credits
SELECT
	SUM(CompleteHSRecords) AS CompleteHSRecords,
	COUNT(*) 
FROM #CompleteHSRecordsUsingMinCredits
```

**Comment by jmhernan** [comment]
Thanks! @codeforkjeff
